org: adasarpan
app: natours-api-dynamo
service: natours-api-dynamo
frameworkVersion: "3"

custom:
  userTableName: "user-table-${sls:stage}"
  tourTableName: "tour-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [ToursTable, Arn]
  environment:
    USERS_TABLE: ${self:custom.userTableName}
    TOURS_TABLE: ${self:custom.tourTableName}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.userTableName}
    ToursTable:
      Type: AWS::DynamoDB::Table
      Properties: # Correct indentation
        AttributeDefinitions: # Correct indentation
          - AttributeName: tourId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: tourId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tourTableName}
